### ISSUE TITLE
FivePDAudio.sln

### ISSUE THREAD

**Issue by FirefighterKyle** [PBogi/FivePDAudio#1]
Getting error where it can't find CitizenFX, Newtonsoft, & JObject. So I can't build it to get the .dll

**Comment by GrandpaRex** [comment]
Did you download the NuGit packages needed?

**Comment by FirefighterKyle** [comment]
No? There was nothing in the readme about it. Will look into the NuGit?

**Comment by PBogi** [comment]
Hi Kyle, sorry for the late reply. I uploaded the latest version (from 2020) here on github (but without the game audio). Hope this helps!

**Comment by rasa2k** [comment]
Hi @PBogi,
Can you give an examples of what goes here: AudioLibrary.cs
// config
public static JObject configuredCallouts = new JObject();
